#!/bin/sh

x=$1
y=$2

set -- $(xwininfo -root| awk -F '[ :]+' '/ (Width|Height):/ { print $3 }')
width=$1
height=$2

wmctrl -r :ACTIVE: -e 0,$(((width/4)*x)),$((((height+20)/2)*y)),$((width/4)),$(((height/2)-30))
